var map=L.map("map").fitWorld().setView([53.773056,20.476111],12);L.tileLayer.wms("https://msipmo.olsztyn.eu/arcgis/services/msipmo_Plan/MapServer/WMSServer?",{layers:"0,1,2,3,4,5,6,7,8,9,10,11,12",tileSize:256,format:"image/png",maxZoom:16}).addTo(map);function onLocationFound(a){L.circle(a.latlng,a.accuracy/2).addTo(map)}map.on("locationfound",onLocationFound);map.locate({setView:!1,maxZoom:16});var availableRoutes,vehiclesLayerGroups=[];
function InternalVehicle(a){(this.stall=0===a.route.length)?(this.route=a.next_route,this.trip_id=a.next_trip_id,this.description=a.next_description,this.vector=0):(this.route=a.route,this.trip_id=a.trip_id,this.description=a.description,this.vector=180+a.vector);this.latitude=a.latitude;this.longitude=a.longitude;this.variance=a.variance;this.isStall=function(){return this.stall};this.getMarker=function(){}}
function serializeVehicles(a){var b=[];a.forEach(function(a){b.push(new InternalVehicle(a))});return b}
function getVehicleIcon(a){var b=a.vector;a:{switch(a.route){case "N01":case "N02":var e="rgba(0, 0, 0, 0.9)";break a;case "1":case "2":case "3":e="rgba(227, 30, 30, 0.9)";break a}e="rgba(0, 157, 210, 0.9)"}var d=a.variance;d=-120<d?"white":-600<d?"yellow":"orange";var c=a.isStall()?"2,2":"0,0";return L.Util.template('<svg width="26" height="26">\n<path transform="rotate({rotate} 13 19)" fill="{fill}" stroke="{stroke}" stroke-width="2"\nstroke-dasharray="{stroke_dasharray}" d="\nM26\n19c0-2.2-0.6-4.4-1.6-6.2C22.2\n8.8\n13\n0\n13\n0S3.8\n8.7\n1.6\n12.8c-1\n1.8-1.6\n4-1.6\n6.2c0\n7.2\n5.8\n13\n13\n13\nS26\n26.2\n26\n19 Z"/>\n<g>\n<text x="13" y="19" font-family="sans-serif" font-size="12px" fill="white"\ntext-anchor="middle" alignment-baseline="central">{route}\n</text>\n</g>\nSorry, your browser does not support inline SVG.\n</svg>',{rotate:b,
fill:e,stroke:d,stroke_dasharray:c,route:a.route})}
function markerizeVehicles(a){var b=[];a.forEach(function(a){var d={icon:L.divIcon({html:getVehicleIcon(a),className:"outerVehicleIcon"}),alt:a.route,riseOnHover:!0,title:a.description},c={route:a.route,trip_id:a.trip_id,description:a.description};a.isStall()?(c.state="Czas do odjazdu",c.variance=a.variance):(c.state="Op\u00f3\u017anienie",c.variance=-1*a.variance);b.push(L.marker([a.latitude,a.longitude],d).bindPopup(L.Util.template("<b>Linia nr {route}</b><br>Numer kursu: {trip_id}<br>Kierunek: {description}<br>{state}: {variance}s",c)))});
return b}function insertOnMap(a){var b=serializeVehicles(a),e=markerizeVehicles(b);availableRoutes.forEach(function(a){vehiclesLayerGroups[a.route].clearLayers();for(var c=0;c<b.length;c++)b[c].route===a.route&&vehiclesLayerGroups[a.route].addLayer(e[c])})}
function fireNextRefresh(a){a=22E3-(Date.now()-a);0>a?-21E3<a?setTimeout(refreshMap,1E3):console.log("Refreshing the map has been stalled. This can happen when there's a problem with the data source. Reload the page to start the refreshing again."):setTimeout(refreshMap,a)}
function refreshMap(){fetch("https://api.autobusy.olsztyn.pl/Vehicles").then(function(a){var b=new Date(a.headers.get("Last-Modified"));fireNextRefresh(b);return a.json()}).then(function(a){insertOnMap(JSON.parse(JSON.stringify(a)))})}
function initializeMap(){fetch("https://api.autobusy.olsztyn.pl/Routes").then(function(a){return a.json()}).then(function(a){availableRoutes=JSON.parse(JSON.stringify(a));availableRoutes.forEach(function(a){vehiclesLayerGroups[a.route]=new L.LayerGroup});L.control.layers(null,vehiclesLayerGroups).addTo(map).expand();refreshMap()})}initializeMap();
