var availableRoutes,vehiclesLayerGroups=[];function InternalVehicle(a){(this.stall=0===a.route.length)?(this.route=a.next_route,this.trip_id=a.next_trip_id,this.description=a.next_description,this.azimuth=0):(this.route=a.route,this.trip_id=a.trip_id,this.description=a.description,this.azimuth=180+a.azimuth);this.latitude=a.latitude;this.longitude=a.longitude;this.variance=a.variance;this.isStall=function(){return this.stall};this.getMarker=function(){}}
function serializeVehicles(a){var b=[];a.forEach(function(a){b.push(new InternalVehicle(a))});return b}
function getVehicleIcon(a){var b=a.azimuth;a:{switch(a.route){case "N01":case "N02":var d="rgba(0, 0, 0, 0.9)";break a;case "1":case "2":case "3":d="rgba(227, 30, 30, 0.9)";break a}d="rgba(0, 157, 210, 0.9)"}var e=a.variance;e=-120<e?"white":-600<e?"yellow":"orange";var c=a.isStall()?"2,2":"0,0";return L.Util.template('<svg class="outerVehicleIcon" width="26" height="26">\n<path transform="rotate({rotate} 13 19)" fill="{fill}" stroke="{stroke}" stroke-width="2"\nstroke-dasharray="{stroke_dasharray}" d="\nM26\n19c0-2.2-0.6-4.4-1.6-6.2C22.2\n8.8\n13\n0\n13\n0S3.8\n8.7\n1.6\n12.8c-1\n1.8-1.6\n4-1.6\n6.2c0\n7.2\n5.8\n13\n13\n13\nS26\n26.2\n26\n19 Z"/>\n<g>\n<text x="13" y="19" font-family="sans-serif" font-size="12px" fill="white"\ntext-anchor="middle" alignment-baseline="central">{route}\n</text>\n</g>\nSorry, your browser does not support inline SVG.\n</svg>',{rotate:b,
fill:d,stroke:e,stroke_dasharray:c,route:a.route})}function betterSeconds(a){if(60<a){var b=Math.floor(a/60);a-=60*b;if(60<b){var d=Math.floor(b/60);return L.Util.template("{HH}h {MM}m {SS}s",{HH:d,MM:b-60*d,SS:a})}return L.Util.template("{MM}m {SS}s",{MM:b,SS:a})}return L.Util.template("{SS}s",{SS:a})}
function markerizeVehicles(a){var b=[];a.forEach(function(a){var d={icon:L.divIcon({html:getVehicleIcon(a),className:"innerVehicleIcon"}),alt:a.route,riseOnHover:!0,title:a.description},c={route:a.route,trip_id:a.trip_id,description:a.description};a.isStall()?0<a.variance?(c.state="Czas do odjazdu",c.variance=betterSeconds(a.variance)):(c.state="Op\u00f3\u017anienie odjazdu",c.variance=betterSeconds(-1*a.variance)):0<a.variance?(c.state="Przed czasem",c.variance=betterSeconds(a.variance)):(c.state=
"Op\u00f3\u017anienie",c.variance=betterSeconds(-1*a.variance));b.push(L.marker([a.latitude,a.longitude],d).bindPopup(L.Util.template("<b>Linia nr {route}</b><br>Numer kursu: {trip_id}<br>Kierunek: {description}<br>{state}: {variance}",c)))});return b}function insertOnMap(a){var b=serializeVehicles(a),d=markerizeVehicles(b);availableRoutes.forEach(function(a){vehiclesLayerGroups[a.route].clearLayers();for(var c=0;c<b.length;c++)b[c].route===a.route&&vehiclesLayerGroups[a.route].addLayer(d[c])})}
function fireNextRefresh(a){a=22E3-(Date.now()-a);0>a?-21E3<a?setTimeout(refresh,1E3):console.log("Refreshing the map has been stalled. This can happen when there's a problem with the data source. Reload the page to start the refreshing again."):setTimeout(refresh,a)}function refresh(){fetch("https://api.autobusy.olsztyn.pl/Vehicles").then(function(a){var b=new Date(a.headers.get("Last-Modified"));fireNextRefresh(b);return a.json()}).then(function(a){insertOnMap(JSON.parse(JSON.stringify(a)))})}
function entrypoint(){var a=L.map("map",{attributionControl:!1}).setView([53.773056,20.476111],14);L.tileLayer("https://api.mapbox.com/styles/v1/amwolff/cjnynkofj1jxf2ro9v4123t0v/tiles/256/{z}/{x}/{y}?access_token={t}",{t:"pk.eyJ1IjoiYW13b2xmZiIsImEiOiJjamtndGVqMnUwbjV2M3BueDRxNWtqODQ5In0.f6Sd2mM-5ozz45F4ZxlU8Q",minZoom:9,maxZoom:18}).addTo(a);L.control.attribution({prefix:!1,position:"bottomright"}).addAttribution('<a href="mailto:kontakt@autobusy.olsztyn.pl">Zg\u0142o\u015b b\u0142\u0105d</a> / \u00a9 <a href="https://www.mapbox.com/about/maps/">Mapbox</a> \u00a9 <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>').addTo(a);
var b;a.on("locationfound",function(d){var e=d.accuracy/2;a.hasLayer(b)?b.setLatLng(d.latlng).setRadius(e):(b=L.circle(d.latlng,{radius:e,color:"#FF6C00"}).addTo(a),a.flyToBounds(b.getBounds(),{maxZoom:17}))});a.on("locationerror",function(a){console.log(a.message)});a.locate({watch:!0,enableHighAccuracy:!0});fetch("https://api.autobusy.olsztyn.pl/Routes").then(function(a){return a.json()}).then(function(b){availableRoutes=JSON.parse(JSON.stringify(b));availableRoutes.forEach(function(a){vehiclesLayerGroups[a.route]=
new L.LayerGroup});L.control.layers(null,vehiclesLayerGroups).addTo(a).expand();refresh()})}entrypoint();
