sudo: false
language: go
go:
- 1.x
- master
matrix:
  allow_failures:
  - go: master
  fast_finish: true
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
script:
# - diff -u <(echo -n) <(gofmt -d -s .)
- go tool vet .
- go test -v -race ./...