sudo: false
language: go
go:
- 1.x
- master
matrix:
  allow_failures:
  - go: master
  fast_finish: true
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
install:
- # Prevent travis-ci from calling its default scripts
script:
- diff -u <(echo -n) <(gofmt -d -s $(go list -f '{{ .Dir }}' ./... | grep -v /vendor/))
- go vet $(go list ./... | grep -v /vendor/)
- go test -v -race ./...
